# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        mvn package
    - name: Upload jar to TianYi cloud server
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        scp_source: discovery-platform-application/target/discovery-platform-application-1.0.0.jar
        scp_target: /usr/opt/platform
        host: ${{secrets.TIANYI_SERVER_IP}}
        username: ${{secrets.TIANYI_SERVER_USER}}
        password: ${{secrets.TIANYI_SERVER_PWD}}
    - name: Deploy to TianYi cloud server
      uses: fifsky/ssh-action@master
      with:
        host: ${{secrets.TIANYI_SERVER_IP}}
        user: ${{secrets.TIANYI_SERVER_USER}}
        pass: ${{secrets.TIANYI_SERVER_PWD}}
        command: cd /usr/opt/platform && nohup ./platform-start.sh &
